name: example
description: One page, with root adaptation on or off, for visual comparison.
publish_to: none
version: 2.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter
  screen_size_adapter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
